### ISSUE TITLE
Error on accessing /charts running app.py

### ISSUE THREAD

**Issue by minimaxir** [christabor/flask_jsondash#49]
After hitting: http://127.0.0.1:5002/charts/

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maxwoolf/Downloads/flask_jsondash-master/flask_jsondash/charts_builder.py", line 182, in dashboard
    opts.update(limit=pagination.limit, skip=pagination.skip)
AttributeError: 'NoneType' object has no attribute 'limit'
```

Not sure how to address.

**Comment by christabor** [comment]
Looks like an issue with the paginator named tuple. I'll take a look.

**Comment by christabor** [comment]
What method did you use to start the app up -- via pypi installation + import, or clone from github + run included app?

**Comment by minimaxir** [comment]
Clone, `python setup.py install` for dependencies, then `python app.py`.

**Comment by christabor** [comment]
Ok thanks, I'll have a look. Just by chance, does this happen if you do an install via pypi and then import it into your own app (you'll have to have a python app importing the module, as well as the right template variables set - this repo has examples of that setup at the top level). 

I just did a test using the above method and it appears to work fine, so I'm guessing it might have something to do with the local setuptools install.

**Comment by christabor** [comment]
Did some testing so far, and the following methods seem to work:


## Method 1 - virtualenv + setuptools

```
git clone https://github.com/christabor/flask_jsondash.git jsondash-test
cd jsondash-test
virtualenv env
source env/bin/activate
python setup.py install
python app.py
```

then to test:
```
curl -XGET http://localhost:5002
<a href="/charts">Visit the charts blueprint.</a>%
```

## Method 2 - pypi + local app

```
mkdir jsondash-test ; cd jsondash-test
virtualenv env
source env/bin/activate
pip install flask-jsondash
```

(then, copying the example app and templates from a different dir)

```
cp -r ../flask_jsondash/templates ../flask_jsondash/app.py .
python app.py
```

then to test:
```
curl -XGET http://localhost:5002
<a href="/charts">Visit the charts blueprint.</a>%
```
